[connections.snowflake]
account = "vjkkjsf-ytb77365"
user = "abhinavsrivastav364"
password = "your-password-here"
role = "SYS_ADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true

